# Generated by Django 4.2.29 on 2026-03-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=300)),
                ('specialization', models.TextField()),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('orthodontics', 'Orthodontics'), ('implants', 'Dental Implants'), ('cosmetic', 'Cosmetic Dentistry'), ('general', 'General Dentistry'), ('pediatric', 'Pediatric Dentistry'), ('surgery', 'Oral Surgery')], max_length=50)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('review', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='Google', help_text='e.g. Google, Practo', max_length=50)),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('before_after', 'Before & After'), ('clinic', 'Clinic'), ('team', 'Team')], max_length=50)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='gallery/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='gallery/after/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
        ),
    ]
